server:
  port: 5858
spring:
  application:
    name: adminserver
logging:
  file:
    name: microservice-adminserver-5858.log
  level: 
    org.springframework.boot.env.PropertySourcesLoader: TRACE
    org.springframework.web: INFO

management:
  metrics:
    web: 
      server:
        request:
          autotime:
            enabled: false
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8888/eureka/
#  instance:
#    hostname: ${spring.cloud.client.ip-address}
#    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
